name: Hike The Hike
title: Hike the Hike with Hudson | A blog for the AT
description: Follow Hudson as he Hikes the Appalachian Trail!
tags:
  - blog
  - AT
  - jekyll
  - theme
  - netlify
  - Appalachian Trail
  - Hiking
  - Camping
  - Through Hiking
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: AT Map
    url: /atmap
email: hb
# See: https://disqus.com/
disqus_username: https-huddleshouse-netlify-app
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id:
