name: Huddles House
title: Huddles House | A blog for the AT
description: Huddles House is based on a template for Jekyll inspired by Netflix and made by
  Thiago Rossener.
tags:
  - blog
  - AT
  - jekyll
  - theme
  - netlify
  - Appalachian Trail
  - Hiking
  - Camping
  - Through Hiking
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: hb
# See: https://disqus.com/
disqus_username: https-huddleshouse-netlify-app
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: xkndjqll
